version: '3.10'

services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile_redis
    container_name: r4c.broker
    expose:
      - "6379"
    init: true
    networks:
      - r4c

  beat:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile_celery
    container_name: r4c.beat
    init: true
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - r4c

networks:
  r4c:
    name: r4c.local
    driver: bridge