# Generated by Django 4.2.5 on 2023-10-05 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0002_robot_blocked_robot_sold_alter_robot_id"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="robot_serial",
        ),
        migrations.AddField(
            model_name="order",
            name="robot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="robots.robot",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="serial",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="waiting_answer",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="waiting_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
